<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <DebugType>None</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Core/Monitoredb.CommonCollectors/Monitoredb.CommonCollectors.csproj" />
  </ItemGroup>

</Project>